feat: Add Zsh shell

diff --git a/install-profile b/install-profile
--- a/install-profile
+++ b/install-profile
@@ -1,6 +1,12 @@
-#!/usr/bin/env bash
+#!/bin/bash -i
 
 set -e
+
+# Do not continue until umask is fixed
+if [ "$(umask)" = "0000" ]; then
+  echo "WSL umask was not fixed, cannot continue!"
+  exit 1
+fi
 
 BASE_CONFIG="base"
 CONFIG_SUFFIX=".yaml"
@@ -19,6 +25,11 @@ PLUGIN_DIR="dotbot-plugins"
 cd "${BASE_DIR}"
 git submodule update --init --recursive --remote
 
+# HACK to make dotbot-brew work since Linuxbrew does not add PATH automatically.
+if [[ `which brew` = "" ]]; then
+  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
+fi
+
 
 while IFS= read -r config; do
     CONFIGS+=" ${config}"
@@ -26,10 +37,9 @@ done < "${META_DIR}/${PROFILES_DIR}/$1"
 
 shift
 
-
-"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${META_DIR}/${PLUGIN_DIR}" --plugin-dir "${META_DIR}/${PLUGIN_DIR}/dotbot-brewfile" --plugin-dir "${META_DIR}/${PLUGIN_DIR}/dotbot-pip" -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"
+"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${META_DIR}/${PLUGIN_DIR}" --plugin-dir "${META_DIR}/dotbot-brew" --plugin-dir "${META_DIR}/dotbot-brewfile" --plugin-dir "${META_DIR}/dotbot-pip" -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"
 
 for config in ${CONFIGS} ${@}; do
     echo -e "\nConfigure $config"
-    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${META_DIR}/${PLUGIN_DIR}" --plugin-dir "${META_DIR}/${PLUGIN_DIR}/dotbot-brewfile" --plugin-dir "${META_DIR}/${PLUGIN_DIR}/dotbot-pip" -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
+    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${META_DIR}/${PLUGIN_DIR}" --plugin-dir "${META_DIR}/dotbot-brew" --plugin-dir "${META_DIR}/dotbot-brewfile" --plugin-dir "${META_DIR}/dotbot-pip" -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
 done
