feat: [bash] Add starship and ble.sh and support debug startup time
+ startship install for all users' Login Shell by default

diff --git a/shells/bash/bash_profile b/shells/bash/bash_profile
--- a/shells/bash/bash_profile
+++ b/shells/bash/bash_profile
@@ -1,9 +1,16 @@
 #!/usr/bin/env bash
+# This file will execute FIRST when current shell is Login Shell (bash -l), ssh default is NOT a Login Shell.
+# Search order, first-match will be executed: ~/.bash_profile -> ~/.bash_login -> ~/.profile
+
+source ~/.config/common/init_functions.sh
+
+# unset DEBUG # Disable debug
+# DEBUG=1 # Enable debug
 
 # This does NOT work on macOS, use [[ "$-" =~ 'i' ]] instead
 # iatest=$(expr index "$-" i)
 
-shopt -q login_shell && echo 'This Bash Shell is a Login Shell' || echo 'This Bash Shell is NOT a Login Shell'
+shopt -q login_shell && echo "$(debug_timestamp)This Bash Shell is a Login Shell" || echo "$(debug_timestamp)This Bash Shell is NOT a Login Shell"
 
 # Ensure that a non-login shell has a defined environment.
 if [ -s "$HOME/.profile" ]; then
@@ -99,6 +106,7 @@ export SCM_GIT_IGNORE_UNTRACKED=true
 
 # Load Bash It in Interactive shell only
 if [[ "$-" =~ 'i' ]] && [ -f "$BASH_IT"/bash_it.sh ]; then
+  debug_echo "Loading bash_it..."
   source "$BASH_IT"/bash_it.sh
 fi
 
@@ -117,6 +125,7 @@ fi
 if [[ "$-" =~ 'i' ]]; then
   # Use sensible bash
   if [ -f "$BASHDOTDIR/sensible.bash" ]; then
+    debug_echo "Loading sensible bash..."
     source "$BASHDOTDIR/sensible.bash"
   fi
 fi
@@ -124,6 +133,7 @@ fi
 # Load the shell dotfiles, and then some:
 # * ~/.path can be used to extend `$PATH`.
 # * ~/.extra can be used for other settings you don’t want to commit.
+debug_echo "Loading dotfiles..."
 for file in $BASHDOTDIR/.{path,bash_prompt,exports,functions,extra}; do
   [ -r "$file" ] && [ -f "$file" ] && source "$file";
 done;
@@ -146,6 +156,7 @@ complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes Syste
 
 # Symfony console commands auto completion
 if [ -f ~/.composer/vendor/bin/symfony-autocomplete ]; then
+  debug_echo "Loading completiom: symfony..."
   eval "$(symfony-autocomplete --aliases=c --aliases=surf --aliases=php-cs-fixer --aliases=typo3cms --aliases=typo3console)"
 fi;
 
@@ -158,28 +169,27 @@ PATH="$HOME/bin:$HOME/.local/bin:$PATH"
 # test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
 # test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
 
-if [[ -d $HOME/.linuxbrew/bin ]]; then
-  eval $($HOME/.linuxbrew/bin/brew shellenv)
-  export MANPATH="$(brew --prefix)/share/man:$MANPATH"
-  export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
+if [[ -d $HOME/.linuxbrew/bin ]] || [[ -d /home/linuxbrew/.linuxbrew/bin ]]; then
+  debug_echo "Loading linuxbrew..."
+  if [[ -d $HOME/.linuxbrew/bin ]]; then
+    eval $($HOME/.linuxbrew/bin/brew shellenv)
+  elif [[ -d /home/linuxbrew/.linuxbrew/bin ]]; then
+    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
+  fi
 
-  export CFLAGS="-I$(brew --prefix openssl@1.1)/include"
-  export CPPFLAGS="-I$(brew --prefix openssl@1.1)/include"
-  export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
-fi
+  BREW_PREFIX=$(brew --prefix)
+  export MANPATH="$BREW_PREFIX/share/man:$MANPATH"
+  export INFOPATH="$BREW_PREFIX/share/info:$INFOPATH"
 
-if [[ -d /home/linuxbrew/.linuxbrew/bin ]]; then
-  eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
-  export MANPATH="$(brew --prefix)/share/man:$MANPATH"
-  export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
-
-  export CFLAGS="-I$(brew --prefix openssl@1.1)/include"
-  export CPPFLAGS="-I$(brew --prefix openssl@1.1)/include"
-  export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
+  OPENSSL_PREFIX=$(brew --prefix openssl@1.1)
+  export CFLAGS="-I$OPENSSL_PREFIX/include"
+  export CPPFLAGS="-I$OPENSSL_PREFIX/include"
+  export LDFLAGS="-L$OPENSSL_PREFIX/lib"
 fi
 
 # Init Pyenv
 if [ -d "$HOME/.pyenv/plugins/pyenv-virtualenv" ]; then
+  debug_echo "Loading pyenv..."
   export PATH="$HOME/.pyenv/bin:$PATH"
   eval "$(pyenv init -)"
   eval "$(pyenv virtualenv-init -)"
@@ -187,6 +197,7 @@ fi
 
 # Init rbenv
 if [ -d "$HOME/.rbenv" ]; then
+  debug_echo "Loading rbenv..."
   export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"
   eval "$(rbenv init -)"
 fi
@@ -195,10 +206,20 @@ fi
 # Node.js
 ############
 if [[ -d $HOME/.nodenv ]]; then
+  debug_echo "Loading nodenv..."
   export NODENV_SHIMS=$HOME/.nodenv/shims
   export PATH="$HOME/.nodenv/bin:$NODENV_SHIMS:$PATH"
 
   eval "$(nodenv init -)"
+fi
+
+############
+# ble.sh
+############
+if [[ -f ~/.local/share/blesh/ble.sh ]]; then
+  debug_echo "Loading ble.sh..."
+  # This lines at the top of .bashrc:
+  [[ $- == *i* ]] && source ~/.local/share/blesh/ble.sh --noattach
 fi
 
 # Ensure that a login non-interactive shell has a defined environment.
@@ -206,28 +227,59 @@ shopt -q login_shell && ( [ ! -z "$PS1" ] && [ -s "$HOME/.bashrc" ] ) && source 
 
 if ! [ -f "$HOME/.localrc" ]; then
   touch $HOME/.localrc
+
+  # !MUST escape '$' and back-slash '\'
   cat >> ~/.localrc <<- EOL
+#!/bin/sh
+# This file execute after .bash_profile anf .bashrc, it only create on the first time dotfiles install
+# Use it to persistent your shell customizations.
+
 export VISUAL=nano
 export EDITOR=nano
 
-hash kompose 2>/dev/null && source <(kompose completion bash)
-
 export HH_CONFIG=hicolor         # get more colors
-# if this is interactive shell, then bind hh to Ctrl-r (for Vi mode check doc)
+
+# See https://designcise.com/web/tutorial/what-does-a-dash-in-front-of-a-shell-name-mean
+# !NOTE: output \`-bash\` because it's a login shell
+# echo Current shell: \$0
+if [ -n "\$ZSH_VERSION" ]; then
+  # assume Zsh
+  echo zsh > /dev/null
+elif [ -n "\$BASH_VERSION" ]; then
+  # Bash only, bind not found on zsh
+  # hstr --show-configuration >> ~/.localrc
+  # REMOVED: Already set in sensible.bash
+  # shopt -s histappend              # append new history items to .bash_history
+  # export HISTCONTROL=ignorespace   # leading space hides commands from history
+  # export HISTFILESIZE=10000        # increase history file size (default is 500)
+  # export HISTSIZE=\${HISTFILESIZE}  # increase history size (default is 500)
+  # export PROMPT_COMMAND="history -a; history -n; \${PROMPT_COMMAND}"   # mem/file sync
+  # if this is interactive shell, then bind hh to Ctrl-r (for Vi mode check doc)
+  hash hstr 2>/dev/null && if [[ \$- =~ .*i.* ]]; then bind '"\C-r": "\C-a hh \C-j"'; fi
+
+  hash kompose 2>/dev/null \\
+    && debug_echo "Loading completion: kopose..." \\
+    && source <(kompose completion bash)
+else
+  # assume something else
+  echo other> /dev/null
+fi
+
+# This make sure ble.sh don't blame script exited with non-zero code
+true
 EOL
-  if hash hstr 2>/dev/null; then
-    # hstr --show-configuration >> ~/.localrc
-    # REMOVED: Already set in sensible.bash
-    # shopt -s histappend              # append new history items to .bash_history
-    # export HISTCONTROL=ignorespace   # leading space hides commands from history
-    # export HISTFILESIZE=10000        # increase history file size (default is 500)
-    # export HISTSIZE=${HISTFILESIZE}  # increase history size (default is 500)
-    # export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"   # mem/file sync
-    # MUST escape $ and double quote (")
-    echo "if [[ \$- =~ .*i.* ]]; then bind '\"\C-r\": \"\C-a hh \C-j\"'; fi" >> ~/.localrc
-  fi
 fi
 
 # Use .localrc for SUPER SECRET CRAP that you don't
 # want in your public, versioned repo.
+debug_echo "Loading local profile..."
 [ -f "$HOME/.localrc" ] && source "$HOME/.localrc"
+
+############
+# starship
+############
+# Load after .localrc so KUBE_CONTEXT will available
+hash starship 2>/dev/null && (debug_echo "Loading starship..." && eval "$(starship init bash)")
+
+# ! This line MUST at the end of .bashrc:
+[[ ${BLE_VERSION-} ]] && ble-attach
